site_name: CATENA
site_description: End-to-end pipelines for large-scale connectomics
repo_url: https://github.com/Mohinta2892/catena-docs.github.io
copyright: "Copyright (c) Samia Mohinta"
#docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Why the name CATENA?: why_name_it_catena.md
  - Modules:
      - EM Mask Generation:
          - Overview: modules/em-mask-generation/index.md
          - Design Choices: modules/em-mask-generation/design-choices.md
      - Local Shape Descriptors:
          - Overview: modules/local-shape-descriptors/index.md
          - Design Choices: modules/local-shape-descriptors/design-choices.md
      - Synapse Detection:
            - Synful:
                - Overview: modules/synful/index.md
                - Design Choices: modules/synful/design-choices.md
            - SimpSyn:
                - Overview: modules/simpsyn/index.md
                - Design Choices: modules/simpsyn/design-choices.md
      - Mitochondria Segmentation:
          - Overview: modules/mitochondria-segmentation/index.md
          - Design Choices: modules/mitochondria-segmentation/design-choices.md
      - Neurotransmitter Classification:
          - Overview: modules/neurotransmitter-classification/index.md
          - Design Choices: modules/neurotransmitter-classification/design-choices.md
      - Proofreading:
          - Overview: modules/proofreading/index.md
          - Design Choices: modules/proofreading/design-choices.md
      - Visualize:
          - Overview: modules/visualize/index.md
          - Design Choices: modules/visualize/design-choices.md

extra_css:
  - stylesheets/overrides.css
